# Generated by Django 4.0.6 on 2022-08-04 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=100)),
                ('task_description', models.CharField(max_length=1000)),
                ('task_status', models.CharField(choices=[('Pending', 'Pending'), ('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=100)),
                ('date_assigned', models.DateField()),
                ('task_reward', models.PositiveIntegerField()),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chores.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.household')),
            ],
        ),
    ]
