# Generated by Django 4.0.6 on 2022-08-13 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_person_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Complete', 'Complete'), ('Incomplete', 'Incomplete'), ('Pending', 'Pending')], default='Incomplete', max_length=100),
        ),
        migrations.CreateModel(
            name='ClaimedReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.person')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.household')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chores.reward')),
            ],
        ),
    ]
